module.exports.descriptors = [
    'Pop',
    'Electronic',
    'Rock',
    'Metal',
    'Hip-Hop',
    'R&B',
    'Jazz',
    'Blues',
    'Alternative',
    'Jam',
    'Folk',
    'Bluegrass',
    'Indie',
    'House',
    'House',
    'Techno',
    'Drum & Bass',
    'Trance',
    'Bass',
    'Hardstyle',
    'Small',
    'Medium',
    'Large',
    'Mega'
]

module.exports.places = [
    'Flats',
    'Town',
    'Canyon',
    'Cruise Ship',
    'Beach Festival',
    'Downtown Festival',
    'Ghost Town',
    'Festival',
    'Indoor Festival',
    'Backcountry',
    'Underground',
    'Summer',
    'Winter',
    'Bay',
    'Spring',
    'Bayshore',
    'Sands',
    'Ski Resort',
    'Island',
    'Cliffs',
    'Cavern'
]